const inputName = document.getElementById(`inputName`)
const inputCPF = document.getElementById(`inputCPF`)
const inputAddress = document.getElementById(`inputAddress`)
const inputCod = document.getElementById(`inputCod`)
const inputTel = document.getElementById(`inputTel`)
const inputCEP = document.getElementById(`inputCEP`)
const inputGen = document.getElementById('inputGen')
const inputBirth = document.getElementById('inputBirth')
const inputState = document.getElementById('inputState')
const inputSchool = document.getElementById('inputSchool')
const inputStatus = document.getElementById('inputStatus')
const inputChild = document.getElementById('inputChild')
const inputWork = document.getElementById('inputWork')
const inputGains = document.getElementById('inputGains')
const inputMoney = document.getElementById('inputMoney')
const inputDestiny = document.getElementById('inputDestiny')

console.log(inputName.value)